language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key: 53e73846-387b-4032-a732-fa353916c275
  app: fit-tracker
  on:
    repo: dsawyer13/fit-tracker
