language: node_js
node_js: node
cache:
  directories:
  - node_modules
install:
  - npm install
script:
  - npm start
  - npm test
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: i07Mja1bSWNlyK/djSF808CWs1pMYAObUNnS9xhJwDGEvrLKgnHGQmDVg/ie76wECWw9a+1P0XqXqycSOFy0iT3v6iko0K5RAZm+X5Vrp2ueSpGzN983xnVilucqgdleuGHNXPRak7txxtUPS+hxZNciMPZ0AM1kCw88bTpAiWXWOtzo0pgqLZyHj+xR1cxCF6Lhhfs0+7LRjgf3WfisMLqtW6tMY0mzNg8qtP5pt52A4jUrcdwNTtVBgTU8tlU94xVT0jlOBYHiqFBs4gckHqkq9Oqq+6rn7AaHLUNreX8sQKmlD9BVhwNz21X4VgcgeTdd39mBts/RJT/IINn0VZTGQ/UBH9kFIi5wUUYnjDHBA3xXWJGjEJxxvL3+QBC74qQpR+w1GGASvKDxS2A6k/PBVf0y6sGUX2fli4A5SjGjXrEu+BSPpGw+WaYDawNKbl2w55+uBcVkS6bTFLCEwFFHebGrylg3fkGv3FSI0XTh+QuXmAOHJoQsTjlu8IAQg3ArfBsDn3OdlQHEubXocdMm21QLa5SfwERjc4UaeS+q1OUdpvZyY9T6S0WUkkJUP3ZA0nzRRSabCHqorVXBTwQrkxLQ3JjGmZZGhKwKcICNwThh6BwEL/zqqEgZuipnObvThacECNpNYnM2qmsuM9zbjOPHtSTTpiFTtqYzfJU=
  app: fit-tracker
  on:
    repo: dsawyer13/fit-tracker
