language: node_js
node_js: node
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm start
- npm test
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: j+8cGtFrKwJNiUyWnNANGyKFzSMTCHBX02gnDLXonfi2RIvp+Tx+sN7NqQNlf39rAs5olla4NdBAvq9Mt3zPGgnzAWhrnJmIJoe/bnGsshwHrhHRvDdxvI9ZW6Ff7Uqh5UgF3t4J1j90lVbJ9uRZEA6zyZqDyd3/U4G44ebDeKoWNoKq73QFBY0Gk4P6dzSVBINTGJLYdnnpqPlYgtNia5N1A4+7ANZR68OdgADQL8dsTieFF3ZdoaixHncW2be3KzCJsbqoiDTpnGjiATgBPCNLgyQFVOaoEFhmkoBzcZXIk1xu1nw1TKLPhRBQn5SXY3ALm7xnB+B5TsFOv3S6wOCQkYC+wg6A/R5exa+Em0GhVbyAdwbDVF48ZUKuIdFjHGnE7Iaki66DPEbRFcqTxF1nxqKFuJ7egj6gSvgh96rZ+aNJZTi22jPxNEWMSvF9IkRaAKEjOAQI+HkSNsAyIf6MDYu4dWHlHrxtDxtR/m07VAl04VLN9q+SmUzPJfdF5S6OWTFOvKKUaFqmTr25YLah+ivo36vCdXn1dmRfObTmOz55A4snlFsMicbAxe/oiVmFCABPAe8oLKZS/xdUbJNj0RDF3TerXhLFh9stiAzd3cQaiaEKQK2XHSKvyVa+7d+hcE32/jfCVtRHgrZMQkY5FPT4jHHtQ3MzCCA/wHw=
  app: fit-tracker
  on:
    repo: dsawyer13/fit-tracker
