language: node_js
node_js: node
cache:
   directories:
     - node_modules
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: lf/30gEIzzZzMwcvSJxKZbZjVauNA1nOfz2uoOJP9W8GhgSBRxM7gor0TTlsoaVEC1YTM9Tv5AhaypUs25xxfgArvLildZ7V3dSF4guCRytXKpquuShbBjHEq0wypW2QTxY4mB1gcwEJcnOnvJ0bPsueelqcAuWcviFmLfablPC4TVOueQfL2Ruk7qHSneYe03AoxJQwaYd4lvEj4Sjq9Sopo95SeEiES9jOPMvOhpq4GQaiyFwzSy6DZ5SRkRZYgHA45efUcdUascxreGSyHtPwPvwpXaFOAaOurJSWZ2fLpVsnzrE31aaoo4M2xcr8XnpOs/njnnBZTKggGuFw1khPqwY4I9VLC8yW7k2BNU9HTiVedBsvGwHJlKrC9yd+L14jifj3mRnRT/LrIzG42UMQ4LqyiSLRbDjWVNqOIqxe6NVbOdgJuxWYSO+LzyLzsPzNxxT3hBkNlm2LO8t8LAA0Vdrx6NWjW7Ecr9iMucn0xSidpfoJgOxzg9xDebRjAeKpY0xFFVWoqPEFnD2IJoto3kC2t7Xek/f/jkvNi7qM/Wtoaz2cbUM8+dASbu0huvXtkiebIXBb/uP7KPbaLZj4Iv8aFGLlqqJm6EBBz5W10HbGs10sb5aw+UZKByodMyUwkn5zFxjpG9H8BDGlrF7xNmMY6DiCbyp2TuORONs=
  app: fit-tracker-api
  on:
    repo: dsawyer13/fit-tracker-api
